# Generated by Django 5.2.2 on 2025-06-20 08:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='card_short_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
