# Generated by Django 5.2.2 on 2025-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0002_hand_card_short_codes_delete_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='hand_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
