# Generated by Django 5.2.2 on 2025-06-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0003_remove_hand_hand_id_alter_player_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='hand_id',
            field=models.IntegerField(default=0),
        ),
    ]
