# Generated by Django 5.2.2 on 2025-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0004_hand_hand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_bet',
        ),
        migrations.AddField(
            model_name='hand',
            name='current_bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
