# Generated by Django 5.2.2 on 2025-06-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0005_remove_player_current_bet_hand_current_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='hand_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
