# Generated by Django 5.2.2 on 2025-06-21 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0008_alter_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='card_short_codes',
        ),
        migrations.AddField(
            model_name='hand',
            name='card_details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
