# Generated by Django 5.2.2 on 2025-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0009_remove_hand_card_short_codes_hand_card_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='current_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
