# Generated by Django 5.2.2 on 2025-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha', '0012_dealer_is_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='special_condition',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
